### ISSUE TITLE
ModuleNotFoundError: No module named 'AuthentiCT.contamination_est'

### ISSUE THREAD

**Issue by XiaoleLei** [StephanePeyregne/AuthentiCT#5]
Hi Stephane，

After installing AuthentiCT, I encountered the following bug when running it. I would greatly appreciate it if you could provide some help. Thank you very much.

--- bug ---
$./AuthentiCT.py -h
Traceback (most recent call last):
  File "./AuthentiCT.py", line 3, in <module>
    from AuthentiCT.cli import main
  File "/data1/apps/AuthentiCT/AuthentiCT-1.0.0/AuthentiCT/cli.py", line 16, in <module>
    from .contamination_est import compute_loglikelihood, format_loglikelihood
ModuleNotFoundError: No module named 'AuthentiCT.contamination_est'
--- bug ---

**Comment by JuPrgn** [comment]
Hello, 

Could you please explain how you installed the library? 
Could you provide the command you used in the terminal that brought up this issue? 
Additionally, can you tell me what's inside the 'build' directory after the package installation?
